$hostsfile = <<-SCRIPT
echo "192.168.99.10   ansible.mydomain.com   ansible" >> /etc/hosts
echo "192.168.99.11   node1.mydomain.com     node1" >> /etc/hosts
echo "192.168.99.12   node2.mydomain.com     node2" >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  # Configurações globais para todas as máquinas
  config.vm.box = "generic/rocky9"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
    vb.cpus = "2"
  end

  # Máquina 1: Ansible Control Node
  config.vm.define :ansible do |ansible|
    ansible.vm.hostname = "ansible.mydomain.com"
    ansible.vm.network :private_network, ip: "192.168.99.10"
    ansible.vm.provision "shell", inline: $hostsfile
  end

  # Máquina 2: Node 1
  config.vm.define :node1 do |node1|
    node1.vm.hostname = "node1.mydomain.com"
    node1.vm.network :private_network, ip: "192.168.99.11"
    node1.vm.provision "shell", inline: $hostsfile
  end

  # Máquina 3: Node 2
  config.vm.define :node2 do |node2|
    node2.vm.hostname = "node2.mydomain.com"
    node2.vm.network :private_network, ip: "192.168.99.12"
    node2.vm.provision "shell", inline: $hostsfile
  end
end

